# Generated by Django 3.1.12 on 2025-04-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
