# Generated by Django 3.1.12 on 2025-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book单数名', 'verbose_name_plural': 'Book复数名'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='书名'),
        ),
    ]
