# #这里面括号内的所有内容如果没有特殊说明，写代码时不能代入，若可代入会特殊说明，若括号内无内容，则写代码时不能写东西
# #第一部分：格式化
# a=''
# n=0
# a.capitalize()#首字母大写
# a.casefold()#全小写
# a.lower()#全小写
# a.upper()#全大写
# a.swapcase()#大小写互换，其中swap的中文意思为交换
# a.center(__width=,__fillchar=)#width指的是将字符长度改为...，fillchar就是长度不足时的填充物，作用是居中字符，两边用指定字符填充
# a.ljust(__width=,__fillchar=)#width指的是将字符长度改为...，fillchar就是长度不足时的填充物，作用是字符居左并右边用指定字符填充
# a.rjust(__width=,__fillchar=)#width指的是将字符长度改为...，fillchar就是长度不足时的填充物，作用是字符居右并左边用指定字符填充
# a.zfill(__width=)#width指的是将字符长度改为...，作用是字符居右并左边用0填充
# a.expandtabs(tabsize=)#tabsize指的是tab键的延升长度，作用是延长tab键的距离，注：其中tabsize可写可不写
# a.title()#每个单词首字母大写
# a.strip()#两边去死皮
# a.lstrip()#左边去死皮
# a.rstrip()#右边去死皮
# a.format(变量1=，变量2=，........，变量n=)#用来给字符串中的待定数值，引用外部变量,字符内部变量用大括号括起来
# #第二部分：判断
# a.startswith('')#判断是否为该字符开头，返回True或者False
# a.endswith('')#判断是否为该字符结尾，返回True或者False
# a.isalpha()#判断是否为字符，注：都是字符串类型，故是判断引号内内容本身的特征，返回True或者False
# a.isnumeric()#判断是否为数字，注：都是字符串类型，故是判断引号内内容本身的特征，返回True或者False
# a.isalnum()#判断是否为字符或者数字，注：都是字符串类型，故是判断引号内内容本身的特征，返回True或者False
# a.isdigit()#判断是否为数字
# a.isdecimal()#判断是否为小数，据说不好用，注：都是字符串类型，故是判断引号内内容本身的特征，返回True或者False，其中decimal的中文意思为小数
# a.isascii()#判断是否为ascii码，注：都是字符串类型，故是判断引号内内容本身的特征，返回True或者False
# a.isidentifier()#判断是否为py语法关键词
# a.islower()#判断是否为小写
# a.isupper()#判断是否为大写
# a.isprintable()#判断是否为可打印内容
# a.isspace()#判断是否为空格
# a.istitle()#判断是否为标题
# #第三部分：查找
# a.index('',__start=,__end=)#查找左数第一个索引值,sub表示要寻找的对象，start表示从第几个索引开始找，end表示在第几个索引结束查找，只可为正，找不到时报错,当要找到字符末尾时可省略后一项，反之不可
# a.rindex('',__start=,__end=)#查找右数第一个索引值，sub表示要寻找的对象，start表示从第几个索引开始找，end表示在第几个索引结束查找，只可为正，找不到时报错,当要找到字符末尾时可省略后一项，反之不可
# a.find('',__start=,__end=)#查找左数第一个索引值，sub表示要寻找的对象，start表示从第几个索引开始找，end表示在第几个索引结束查找，只可为正，当要找到字符末尾时可省略后一项，反之不可,找不到时输出-1
# a.rfind('',__start=,__end=)#查找右数第一个索引值，sub表示要寻找的对象，start表示从第几个索引开始找，end表示在第几个索引结束查找，只可为正，当要找到字符末尾时可省略后一项，反之不可,找不到时输出-1
# a.count('',__start=,__end=)#记录总共有多少个查找对象，start表示从第几个索引开始找，end表示在第几个索引结束查找，只可为正，当要找到字符末尾时可省略后一项，反之不可
# #第四部分：特殊用法
# a.split('',maxsplit=)#按照引号内内容作为标志分割从左依次分割变为list类型，分割物会消失，maxsplit为最大分割数，maxsplit=可写可不写，split的中文意思为分割
# a.rsplit('',maxsplit=)#按照引号内内容作为标志分割从右依次分割变为list类型，分割物会消失，maxsplit为最大分割数，maxsplit=可写可不写
# a.splitlines()#按照转行分割引号内内容变为list类型
# a.removeprefix(__prefix=)#按要求移除前缀，__prefix表示前缀内容
# a.removesuffix(__prefix=)#按要求移除后缀，__suffix表示前缀内容
# a.replace(__old=,__new=,__count=)#替换指定字符指定次数，old表示要换的，new表示换成的，count表示换的次数
# a.encode('编码方式')#将字符转变为指定编码类型的二进制形式，即python的字节类型
# a.decode('编码方式')#将已转为指定编码类型的字符二进制转回字符
# ''.join([])#将列表中的每个元素之间以引号内的内容连接在一起，并返回字符串
# n.maketrans([],[])#将第一个列表与第二个列表形成映照关系，即一中的一一对应二中的，返回字典类型的，n为随意变量，括号内分别为两个列表，第一个为原文，第二个为对应密文
# a.translate(a.maketrans([],[]))#将a字符串通过前一个生成的字典将字符进行转换，括号内为生成的字典
# '%s/%d/%f'%(变量)，即可引用外部变量，其中s为str，d为整型，f为浮点数